// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Composable, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAccountData, DeleteAccountError, DeleteAccountResponse, DeleteAdminUsersUserIdData, DeleteAdminUsersUserIdError, DeleteAdminUsersUserIdResponse, GetAccountData, GetAccountError, GetAccountResponse, GetAdminUsersData, GetAdminUsersResponse, GetAdminUsersUserIdData, GetAdminUsersUserIdError, GetAdminUsersUserIdResponse, GetAuthSessionData, GetAuthSessionError, GetAuthSessionResponse, GetDevPackagesData, GetDevPackagesPackageNameData, GetDevPackagesPackageNameError, GetDevPackagesPackageNameReleasesData, GetDevPackagesPackageNameReleasesPackageNameData, GetDevPackagesPackageNameReleasesPackageNameError, GetDevPackagesPackageNameReleasesPackageNameResponse, GetDevPackagesPackageNameReleasesResponse, GetDevPackagesPackageNameResponse, GetDevPackagesResponse, PostAccountLogoutData, PostAccountLogoutError, PostAccountLogoutResponse, PostAdminUsersData, PostAdminUsersError, PostAdminUsersResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthLogoutData, PostAuthLogoutError, PostAuthLogoutResponse, PostDevPackagesData, PostDevPackagesError, PostDevPackagesPackageNameReleasesVersionArchData, PostDevPackagesPackageNameReleasesVersionArchError, PostDevPackagesPackageNameReleasesVersionArchResponse, PostDevPackagesResponse, PutAccountData, PutAccountError, PutAccountPasswordData, PutAccountPasswordError, PutAccountPasswordResponse, PutAccountResponse, PutAdminUsersUserIdData, PutAdminUsersUserIdError, PutAdminUsersUserIdPasswordData, PutAdminUsersUserIdPasswordError, PutAdminUsersUserIdPasswordResponse, PutAdminUsersUserIdResponse, PutDevPackagesPackageNameData, PutDevPackagesPackageNameError, PutDevPackagesPackageNameResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * User Login
 *
 * Authenticate a user with their username and password
 */
export const postAuthLogin = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLoginResponse = PostAuthLoginResponse>(options: Options<TComposable, PostAuthLoginData, PostAuthLoginResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthLoginResponse | DefaultT, PostAuthLoginError, DefaultT>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current Session
 *
 * Retrieve the current user's session information
 */
export const getAuthSession = <TComposable extends Composable = '$fetch', DefaultT extends GetAuthSessionResponse = GetAuthSessionResponse>(options: Options<TComposable, GetAuthSessionData, GetAuthSessionResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAuthSessionResponse | DefaultT, GetAuthSessionError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * User Logout
 *
 * Invalidate the current user's session
 */
export const postAuthLogout = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLogoutResponse = PostAuthLogoutResponse>(options: Options<TComposable, PostAuthLogoutData, PostAuthLogoutResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthLogoutResponse | DefaultT, PostAuthLogoutError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Delete account
 *
 * Permanently delete the authenticated user's account.
 */
export const deleteAccount = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAccountResponse = DeleteAccountResponse>(options: Options<TComposable, DeleteAccountData, DeleteAccountResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteAccountResponse | DefaultT, DeleteAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Get account information
 *
 * Retrieve information about the authenticated user's account.
 */
export const getAccount = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountResponse = GetAccountResponse>(options: Options<TComposable, GetAccountData, GetAccountResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAccountResponse | DefaultT, GetAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Update account information
 *
 * Update information about the authenticated user's account.
 */
export const putAccount = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountResponse = PutAccountResponse>(options: Options<TComposable, PutAccountData, PutAccountResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAccountResponse | DefaultT, PutAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change account password
 *
 * Change the password of the authenticated user's account.
 */
export const putAccountPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountPasswordResponse = PutAccountPasswordResponse>(options: Options<TComposable, PutAccountPasswordData, PutAccountPasswordResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAccountPasswordResponse | DefaultT, PutAccountPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout from current session
 *
 * Logs out the authenticated user from the current session.
 */
export const postAccountLogout = <TComposable extends Composable = '$fetch', DefaultT extends PostAccountLogoutResponse = PostAccountLogoutResponse>(options: Options<TComposable, PostAccountLogoutData, PostAccountLogoutResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAccountLogoutResponse | DefaultT, PostAccountLogoutError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/logout',
    ...options
});

/**
 * List packages
 *
 * Retrieve a list of available packages.
 */
export const getDevPackages = <TComposable extends Composable = '$fetch', DefaultT extends GetDevPackagesResponse = GetDevPackagesResponse>(options: Options<TComposable, GetDevPackagesData, GetDevPackagesResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDevPackagesResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dev/packages',
    ...options
});

/**
 * Create a new package
 *
 * Create a new package under the authenticated developer's account.
 */
export const postDevPackages = <TComposable extends Composable = '$fetch', DefaultT extends PostDevPackagesResponse = PostDevPackagesResponse>(options: Options<TComposable, PostDevPackagesData, PostDevPackagesResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostDevPackagesResponse | DefaultT, PostDevPackagesError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dev/packages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get package details
 *
 * Retrieve details of a specific package.
 */
export const getDevPackagesPackageName = <TComposable extends Composable = '$fetch', DefaultT extends GetDevPackagesPackageNameResponse = GetDevPackagesPackageNameResponse>(options: Options<TComposable, GetDevPackagesPackageNameData, GetDevPackagesPackageNameResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDevPackagesPackageNameResponse | DefaultT, GetDevPackagesPackageNameError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dev/packages/{packageName}',
    ...options
});

/**
 * Update package details
 *
 * Update details of a specific package owned by the authenticated developer.
 */
export const putDevPackagesPackageName = <TComposable extends Composable = '$fetch', DefaultT extends PutDevPackagesPackageNameResponse = PutDevPackagesPackageNameResponse>(options: Options<TComposable, PutDevPackagesPackageNameData, PutDevPackagesPackageNameResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutDevPackagesPackageNameResponse | DefaultT, PutDevPackagesPackageNameError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dev/packages/{packageName}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all package releases
 *
 * Retrieve a list of all releases for the specified package.
 */
export const getDevPackagesPackageNameReleases = <TComposable extends Composable = '$fetch', DefaultT extends GetDevPackagesPackageNameReleasesResponse = GetDevPackagesPackageNameReleasesResponse>(options: Options<TComposable, GetDevPackagesPackageNameReleasesData, GetDevPackagesPackageNameReleasesResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDevPackagesPackageNameReleasesResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dev/packages/{packageName}/releases',
    ...options
});

/**
 * Create a new package release
 *
 * Create a new release for the specified package.
 */
export const postDevPackagesPackageNameReleasesVersionArch = <TComposable extends Composable = '$fetch', DefaultT extends PostDevPackagesPackageNameReleasesVersionArchResponse = PostDevPackagesPackageNameReleasesVersionArchResponse>(options: Options<TComposable, PostDevPackagesPackageNameReleasesVersionArchData, PostDevPackagesPackageNameReleasesVersionArchResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostDevPackagesPackageNameReleasesVersionArchResponse | DefaultT, PostDevPackagesPackageNameReleasesVersionArchError, DefaultT>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dev/packages/{packageName}/releases/{version}/{arch}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get package release details
 *
 * Retrieve details of a specific package release.
 */
export const getDevPackagesPackageNameReleasesPackageName = <TComposable extends Composable = '$fetch', DefaultT extends GetDevPackagesPackageNameReleasesPackageNameResponse = GetDevPackagesPackageNameReleasesPackageNameResponse>(options: Options<TComposable, GetDevPackagesPackageNameReleasesPackageNameData, GetDevPackagesPackageNameReleasesPackageNameResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetDevPackagesPackageNameReleasesPackageNameResponse | DefaultT, GetDevPackagesPackageNameReleasesPackageNameError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dev/packages/{packageName}/releases/{packageName}',
    ...options
});

/**
 * List users
 *
 * Retrieve LeiOS accounts with optional role and search filters.
 */
export const getAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersResponse = GetAdminUsersResponse>(options: Options<TComposable, GetAdminUsersData, GetAdminUsersResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAdminUsersResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options
});

/**
 * Create user
 *
 * Provision a new LeiOS account with the desired role.
 */
export const postAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends PostAdminUsersResponse = PostAdminUsersResponse>(options: Options<TComposable, PostAdminUsersData, PostAdminUsersResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAdminUsersResponse | DefaultT, PostAdminUsersError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete user
 *
 * Permanently remove a LeiOS account after verifying it has no owned packages.
 */
export const deleteAdminUsersUserId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAdminUsersUserIdResponse = DeleteAdminUsersUserIdResponse>(options: Options<TComposable, DeleteAdminUsersUserIdData, DeleteAdminUsersUserIdResponse, DefaultT>) => (options.client ?? client).delete<TComposable, DeleteAdminUsersUserIdResponse | DefaultT, DeleteAdminUsersUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Get user
 *
 * Retrieve details for a specific LeiOS account.
 */
export const getAdminUsersUserId = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersUserIdResponse = GetAdminUsersUserIdResponse>(options: Options<TComposable, GetAdminUsersUserIdData, GetAdminUsersUserIdResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetAdminUsersUserIdResponse | DefaultT, GetAdminUsersUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Update user
 *
 * Modify profile fields or role for a LeiOS account.
 */
export const putAdminUsersUserId = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersUserIdResponse = PutAdminUsersUserIdResponse>(options: Options<TComposable, PutAdminUsersUserIdData, PutAdminUsersUserIdResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAdminUsersUserIdResponse | DefaultT, PutAdminUsersUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset user password
 *
 * Set a new password for a LeiOS account and revoke active sessions.
 */
export const putAdminUsersUserIdPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersUserIdPasswordResponse = PutAdminUsersUserIdPasswordResponse>(options: Options<TComposable, PutAdminUsersUserIdPasswordData, PutAdminUsersUserIdPasswordResponse, DefaultT>) => (options.client ?? client).put<TComposable, PutAdminUsersUserIdPasswordResponse | DefaultT, PutAdminUsersUserIdPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
