// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:4000' | 'https://api.leios.dev' | (string & {});
};

export type GetPublicPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/packages';
};

export type GetPublicPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release_amd64: string | null;
            latest_stable_release_arm64: string | null;
            latest_testing_release_amd64: string | null;
            latest_testing_release_arm64: string | null;
        }>;
    };
};

export type GetPublicPackagesResponse = GetPublicPackagesResponses[keyof GetPublicPackagesResponses];

export type GetPublicPackagesPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        repo?: 'leios-archive' | 'leios-testing' | 'leios-stable';
    };
    url: '/public/packages/{packageName}';
};

export type GetPublicPackagesPackageNameErrors = {
    /**
     * Package not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package not found';
    };
};

export type GetPublicPackagesPackageNameError = GetPublicPackagesPackageNameErrors[keyof GetPublicPackagesPackageNameErrors];

export type GetPublicPackagesPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            package: {
                id: number;
                name: string;
                owner_user_id: number;
                description: string;
                homepage_url: string;
                requires_patching: boolean;
                created_at: number;
                latest_stable_release_amd64: string | null;
                latest_stable_release_arm64: string | null;
                latest_testing_release_amd64: string | null;
                latest_testing_release_arm64: string | null;
            };
            releases: {
                'leios-archive': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
                'leios-testing': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
                'leios-stable': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            versionWithLeiosPatch: string;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
            };
        };
    };
};

export type GetPublicPackagesPackageNameResponse = GetPublicPackagesPackageNameResponses[keyof GetPublicPackagesPackageNameResponses];

export type GetPublicPackagesPackageNameReleasesData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        repo?: 'leios-archive' | 'leios-testing' | 'leios-stable';
    };
    url: '/public/packages/{packageName}/releases';
};

export type GetPublicPackagesPackageNameReleasesErrors = {
    /**
     * Package not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package not found';
    };
};

export type GetPublicPackagesPackageNameReleasesError = GetPublicPackagesPackageNameReleasesErrors[keyof GetPublicPackagesPackageNameReleasesErrors];

export type GetPublicPackagesPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: {
            'leios-archive': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                };
            };
            'leios-testing': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                };
            };
            'leios-stable': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        versionWithLeiosPatch: string;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                };
            };
        };
    };
};

export type GetPublicPackagesPackageNameReleasesResponse = GetPublicPackagesPackageNameReleasesResponses[keyof GetPublicPackagesPackageNameReleasesResponses];

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid username or password';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body?: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: unknown & unknown & unknown & unknown;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type PostAuthResetPasswordRequestData = {
    body?: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password/request';
};

export type PostAuthResetPasswordRequestErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAuthResetPasswordRequestError = PostAuthResetPasswordRequestErrors[keyof PostAuthResetPasswordRequestErrors];

export type PostAuthResetPasswordRequestResponses = {
    /**
     * If the username exists, a password reset has been requested
     */
    200: {
        success: true;
        code: 200;
        message: 'If the username exists, a password reset has been requested';
        data: null;
    };
};

export type PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponses[keyof PostAuthResetPasswordRequestResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body?: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: unknown & unknown & unknown & unknown;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAccountApikeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type GetAccountApikeysResponses = {
    /**
     * API keys retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API keys retrieved successfully';
        data: Array<{
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        }>;
    };
};

export type GetAccountApikeysResponse = GetAccountApikeysResponses[keyof GetAccountApikeysResponses];

export type PostAccountApikeysData = {
    body?: {
        description: string;
        expires_at: '7d' | '30d' | '90d' | '180d' | '365d' | null;
    };
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type PostAccountApikeysErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAccountApikeysError = PostAccountApikeysErrors[keyof PostAccountApikeysErrors];

export type PostAccountApikeysResponses = {
    /**
     * API key created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key created successfully';
        data: {
            id: string;
            token: string;
        };
    };
};

export type PostAccountApikeysResponse = PostAccountApikeysResponses[keyof PostAccountApikeysResponses];

export type DeleteAccountApikeysApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type DeleteAccountApikeysApiKeyIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type DeleteAccountApikeysApiKeyIdError = DeleteAccountApikeysApiKeyIdErrors[keyof DeleteAccountApikeysApiKeyIdErrors];

export type DeleteAccountApikeysApiKeyIdResponses = {
    /**
     * API key deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key deleted successfully';
        data: null;
    };
};

export type DeleteAccountApikeysApiKeyIdResponse = DeleteAccountApikeysApiKeyIdResponses[keyof DeleteAccountApikeysApiKeyIdResponses];

export type GetDevPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dev/packages';
};

export type GetDevPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release_amd64: string | null;
            latest_stable_release_arm64: string | null;
            latest_testing_release_amd64: string | null;
            latest_testing_release_arm64: string | null;
        }>;
    };
};

export type GetDevPackagesResponse = GetDevPackagesResponses[keyof GetDevPackagesResponses];

export type PostDevPackagesData = {
    body?: {
        name: string;
        description: string;
        homepage_url: string;
        requires_patching?: boolean;
    };
    path?: never;
    query?: never;
    url: '/dev/packages';
};

export type PostDevPackagesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package with this name already exists';
    };
};

export type PostDevPackagesError = PostDevPackagesErrors[keyof PostDevPackagesErrors];

export type PostDevPackagesResponses = {
    /**
     * Package created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package created successfully';
        data: null;
    };
};

export type PostDevPackagesResponse = PostDevPackagesResponses[keyof PostDevPackagesResponses];

export type GetDevPackagesPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}';
};

export type GetDevPackagesPackageNameErrors = {
    /**
     * Package with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified ID not found';
    };
};

export type GetDevPackagesPackageNameError = GetDevPackagesPackageNameErrors[keyof GetDevPackagesPackageNameErrors];

export type GetDevPackagesPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            id: number;
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release_amd64: string | null;
            latest_stable_release_arm64: string | null;
            latest_testing_release_amd64: string | null;
            latest_testing_release_arm64: string | null;
        };
    };
};

export type GetDevPackagesPackageNameResponse = GetDevPackagesPackageNameResponses[keyof GetDevPackagesPackageNameResponses];

export type PutDevPackagesPackageNameData = {
    body?: {
        id?: number;
        description?: string;
        homepage_url?: string;
        requires_patching?: boolean;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}';
};

export type PutDevPackagesPackageNameErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified ID not found';
    };
};

export type PutDevPackagesPackageNameError = PutDevPackagesPackageNameErrors[keyof PutDevPackagesPackageNameErrors];

export type PutDevPackagesPackageNameResponses = {
    /**
     * Package updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package updated successfully';
        data: null;
    };
};

export type PutDevPackagesPackageNameResponse = PutDevPackagesPackageNameResponses[keyof PutDevPackagesPackageNameResponses];

export type GetDevPackagesPackageNameReleasesData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases';
};

export type GetDevPackagesPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            versionWithLeiosPatch: string;
            architecture: Array<'amd64' | 'arm64'>;
            created_at: number;
        }>;
    };
};

export type GetDevPackagesPackageNameReleasesResponse = GetDevPackagesPackageNameReleasesResponses[keyof GetDevPackagesPackageNameReleasesResponses];

export type GetDevPackagesPackageNameReleasesVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type GetDevPackagesPackageNameReleasesVersionWithLeiosPatchErrors = {
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type GetDevPackagesPackageNameReleasesVersionWithLeiosPatchError = GetDevPackagesPackageNameReleasesVersionWithLeiosPatchErrors[keyof GetDevPackagesPackageNameReleasesVersionWithLeiosPatchErrors];

export type GetDevPackagesPackageNameReleasesVersionWithLeiosPatchResponses = {
    /**
     * Package release retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release retrieved successfully';
        data: {
            id: number;
            package_id: number;
            versionWithLeiosPatch: string;
            architecture: Array<'amd64' | 'arm64'>;
            created_at: number;
        };
    };
};

export type GetDevPackagesPackageNameReleasesVersionWithLeiosPatchResponse = GetDevPackagesPackageNameReleasesVersionWithLeiosPatchResponses[keyof GetDevPackagesPackageNameReleasesVersionWithLeiosPatchResponses];

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release with this version already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release with this version already exists';
    };
};

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchError = PostDevPackagesPackageNameReleasesVersionWithLeiosPatchErrors[keyof PostDevPackagesPackageNameReleasesVersionWithLeiosPatchErrors];

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchResponses = {
    /**
     * Package release created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release created successfully';
        data: null;
    };
};

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchResponse = PostDevPackagesPackageNameReleasesVersionWithLeiosPatchResponses[keyof PostDevPackagesPackageNameReleasesVersionWithLeiosPatchResponses];

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchData = {
    body?: {
        file: Blob | File;
    };
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
        arch: 'amd64' | 'arm64';
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{versionWithLeiosPatch}/{arch}';
};

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release already contains a release for this architecture
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release already contains a release for this architecture';
    };
    /**
     * Failed to upload and verify package release asset
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to upload and verify package release asset';
    };
};

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchError = PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchErrors[keyof PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchErrors];

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchResponses = {
    /**
     * Package release file uploaded successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release file uploaded successfully';
        data: null;
    };
};

export type PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchResponse = PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchResponses[keyof PostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchResponses];

export type GetDevPackagesPackageNameStablePromotionRequestsData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/dev/packages/{packageName}/stable-promotion-requests';
};

export type GetDevPackagesPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string;
        }>;
    };
};

export type GetDevPackagesPackageNameStablePromotionRequestsResponse = GetDevPackagesPackageNameStablePromotionRequestsResponses[keyof GetDevPackagesPackageNameStablePromotionRequestsResponses];

export type PostDevPackagesPackageNameStablePromotionRequestsData = {
    body?: {
        package_release_id: number;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/stable-promotion-requests';
};

export type PostDevPackagesPackageNameStablePromotionRequestsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Release not found in archive repository
     */
    404: {
        success: false;
        code: 404;
        message: 'Release not found in archive repository';
    };
    /**
     * A request already for this release already exists or the release is already stable
     */
    409: {
        success: false;
        code: 409;
        message: 'A request already for this release already exists or the release is already stable';
    };
};

export type PostDevPackagesPackageNameStablePromotionRequestsError = PostDevPackagesPackageNameStablePromotionRequestsErrors[keyof PostDevPackagesPackageNameStablePromotionRequestsErrors];

export type PostDevPackagesPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion request submitted
     */
    201: {
        success: true;
        code: 201;
        message: 'Stable promotion request submitted';
        data: {
            id: number;
        };
    };
};

export type PostDevPackagesPackageNameStablePromotionRequestsResponse = PostDevPackagesPackageNameStablePromotionRequestsResponses[keyof PostDevPackagesPackageNameStablePromotionRequestsResponses];

export type GetDevTasksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/dev/tasks';
};

export type GetDevTasksResponses = {
    /**
     * Scheduled tasks retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'Scheduled tasks retrieved';
        data: Array<{
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        }>;
    };
};

export type GetDevTasksResponse = GetDevTasksResponses[keyof GetDevTasksResponses];

export type GetDevTasksTaskIdData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/dev/tasks/{taskID}';
};

export type GetDevTasksTaskIdErrors = {
    /**
     * Task with specified ID or Tag not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found';
    };
};

export type GetDevTasksTaskIdError = GetDevTasksTaskIdErrors[keyof GetDevTasksTaskIdErrors];

export type GetDevTasksTaskIdResponses = {
    /**
     * Task retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task retrieved successfully';
        data: {
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        };
    };
};

export type GetDevTasksTaskIdResponse = GetDevTasksTaskIdResponses[keyof GetDevTasksTaskIdResponses];

export type GetDevTasksTaskIdLogsData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/dev/tasks/{taskID}/logs';
};

export type GetDevTasksTaskIdLogsErrors = {
    /**
     * Logs are not stored for this task
     */
    400: {
        success: false;
        code: 400;
        message: 'Logs are not stored for this task';
    };
    /**
     * Task with specified ID or Tag not found / Log file not found for this task
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found / Log file not found for this task';
    };
};

export type GetDevTasksTaskIdLogsError = GetDevTasksTaskIdLogsErrors[keyof GetDevTasksTaskIdLogsErrors];

export type GetDevTasksTaskIdLogsResponses = {
    /**
     * Task logs retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task logs retrieved successfully';
        data: {
            logs: string;
        };
    };
};

export type GetDevTasksTaskIdLogsResponse = GetDevTasksTaskIdLogsResponses[keyof GetDevTasksTaskIdLogsResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'developer' | 'user';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body?: {
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'developer' | 'user';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersUserIdErrors = {
    /**
     * Cannot delete user while packages are assigned
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete user while packages are assigned';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersUserIdError = DeleteAdminUsersUserIdErrors[keyof DeleteAdminUsersUserIdErrors];

export type DeleteAdminUsersUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersUserIdResponse = DeleteAdminUsersUserIdResponses[keyof DeleteAdminUsersUserIdResponses];

export type GetAdminUsersUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersUserIdError = GetAdminUsersUserIdErrors[keyof GetAdminUsersUserIdErrors];

export type GetAdminUsersUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type GetAdminUsersUserIdResponse = GetAdminUsersUserIdResponses[keyof GetAdminUsersUserIdResponses];

export type PutAdminUsersUserIdData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'developer' | 'user';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersUserIdError = PutAdminUsersUserIdErrors[keyof PutAdminUsersUserIdErrors];

export type PutAdminUsersUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            created_at: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type PutAdminUsersUserIdResponse = PutAdminUsersUserIdResponses[keyof PutAdminUsersUserIdResponses];

export type PutAdminUsersUserIdPasswordData = {
    body?: {
        /**
         * New password for the account
         */
        password: unknown & unknown & unknown & unknown;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersUserIdPasswordError = PutAdminUsersUserIdPasswordErrors[keyof PutAdminUsersUserIdPasswordErrors];

export type PutAdminUsersUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersUserIdPasswordResponse = PutAdminUsersUserIdPasswordResponses[keyof PutAdminUsersUserIdPasswordResponses];

export type GetAdminPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/packages';
};

export type GetAdminPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release_amd64: string | null;
            latest_stable_release_arm64: string | null;
            latest_testing_release_amd64: string | null;
            latest_testing_release_arm64: string | null;
        }>;
    };
};

export type GetAdminPackagesResponse = GetAdminPackagesResponses[keyof GetAdminPackagesResponses];

export type PostAdminPackagesData = {
    body?: {
        name: string;
        owner_user_id: number;
        description: string;
        homepage_url: string;
        requires_patching?: boolean;
    };
    path?: never;
    query?: never;
    url: '/admin/packages';
};

export type PostAdminPackagesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package with this name already exists';
    };
};

export type PostAdminPackagesError = PostAdminPackagesErrors[keyof PostAdminPackagesErrors];

export type PostAdminPackagesResponses = {
    /**
     * Package created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package created successfully';
        data: null;
    };
};

export type PostAdminPackagesResponse = PostAdminPackagesResponses[keyof PostAdminPackagesResponses];

export type DeleteAdminPackagesPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}';
};

export type DeleteAdminPackagesPackageNameErrors = {
    /**
     * Package with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified ID not found';
    };
};

export type DeleteAdminPackagesPackageNameError = DeleteAdminPackagesPackageNameErrors[keyof DeleteAdminPackagesPackageNameErrors];

export type DeleteAdminPackagesPackageNameResponses = {
    /**
     * Package deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package deleted successfully';
        data: null;
    };
};

export type DeleteAdminPackagesPackageNameResponse = DeleteAdminPackagesPackageNameResponses[keyof DeleteAdminPackagesPackageNameResponses];

export type GetAdminPackagesPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}';
};

export type GetAdminPackagesPackageNameErrors = {
    /**
     * Package with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified ID not found';
    };
};

export type GetAdminPackagesPackageNameError = GetAdminPackagesPackageNameErrors[keyof GetAdminPackagesPackageNameErrors];

export type GetAdminPackagesPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            id: number;
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
            requires_patching: boolean;
            created_at: number;
            latest_stable_release_amd64: string | null;
            latest_stable_release_arm64: string | null;
            latest_testing_release_amd64: string | null;
            latest_testing_release_arm64: string | null;
        };
    };
};

export type GetAdminPackagesPackageNameResponse = GetAdminPackagesPackageNameResponses[keyof GetAdminPackagesPackageNameResponses];

export type PutAdminPackagesPackageNameData = {
    body?: {
        id?: number;
        description?: string;
        homepage_url?: string;
        requires_patching?: boolean;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}';
};

export type PutAdminPackagesPackageNameErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified ID not found';
    };
};

export type PutAdminPackagesPackageNameError = PutAdminPackagesPackageNameErrors[keyof PutAdminPackagesPackageNameErrors];

export type PutAdminPackagesPackageNameResponses = {
    /**
     * Package updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package updated successfully';
        data: null;
    };
};

export type PutAdminPackagesPackageNameResponse = PutAdminPackagesPackageNameResponses[keyof PutAdminPackagesPackageNameResponses];

export type GetAdminPackagesPackageNameReleasesData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases';
};

export type GetAdminPackagesPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            versionWithLeiosPatch: string;
            architecture: Array<'amd64' | 'arm64'>;
            created_at: number;
        }>;
    };
};

export type GetAdminPackagesPackageNameReleasesResponse = GetAdminPackagesPackageNameReleasesResponses[keyof GetAdminPackagesPackageNameReleasesResponses];

export type DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors = {
    /**
     * Package release with specified ID not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified ID not found';
    };
};

export type DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchError = DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors[keyof DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors];

export type DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses = {
    /**
     * Package release deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release deleted successfully';
        data: null;
    };
};

export type DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponse = DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses[keyof DeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses];

export type GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors = {
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchError = GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors[keyof GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors];

export type GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses = {
    /**
     * Package release retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release retrieved successfully';
        data: {
            id: number;
            package_id: number;
            versionWithLeiosPatch: string;
            architecture: Array<'amd64' | 'arm64'>;
            created_at: number;
        };
    };
};

export type GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponse = GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses[keyof GetAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses];

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchData = {
    body?: never;
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}';
};

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release with this version already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release with this version already exists';
    };
};

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchError = PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors[keyof PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchErrors];

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses = {
    /**
     * Package release created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release created successfully';
        data: null;
    };
};

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponse = PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses[keyof PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponses];

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchData = {
    body?: {
        file: Blob | File;
    };
    path: {
        packageName: string;
        versionWithLeiosPatch: string;
        arch: 'amd64' | 'arm64';
    };
    query?: never;
    url: '/admin/packages/{packageName}/releases/{versionWithLeiosPatch}/{arch}';
};

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package release already contains a release for this architecture
     */
    409: {
        success: false;
        code: 409;
        message: 'Package release already contains a release for this architecture';
    };
    /**
     * Failed to upload and verify package release asset
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to upload and verify package release asset';
    };
};

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchError = PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchErrors[keyof PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchErrors];

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchResponses = {
    /**
     * Package release file uploaded successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release file uploaded successfully';
        data: null;
    };
};

export type PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchResponse = PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchResponses[keyof PostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchResponses];

export type GetAdminPackagesPackageNameStablePromotionRequestsData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/admin/packages/{packageName}/stable-promotion-requests';
};

export type GetAdminPackagesPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending';
            created_at: number;
            admin_note: null;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'approved';
            created_at: number;
            admin_note: string | null;
        } | {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'denied';
            created_at: number;
            admin_note: string;
        }>;
    };
};

export type GetAdminPackagesPackageNameStablePromotionRequestsResponse = GetAdminPackagesPackageNameStablePromotionRequestsResponses[keyof GetAdminPackagesPackageNameStablePromotionRequestsResponses];

export type PostAdminPackagesPackageNameStablePromotionRequestsData = {
    body?: {
        package_release_id: number;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/stable-promotion-requests';
};

export type PostAdminPackagesPackageNameStablePromotionRequestsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Release not found in archive repository
     */
    404: {
        success: false;
        code: 404;
        message: 'Release not found in archive repository';
    };
    /**
     * A request already for this release already exists or the release is already stable
     */
    409: {
        success: false;
        code: 409;
        message: 'A request already for this release already exists or the release is already stable';
    };
};

export type PostAdminPackagesPackageNameStablePromotionRequestsError = PostAdminPackagesPackageNameStablePromotionRequestsErrors[keyof PostAdminPackagesPackageNameStablePromotionRequestsErrors];

export type PostAdminPackagesPackageNameStablePromotionRequestsResponses = {
    /**
     * Stable promotion request submitted
     */
    201: {
        success: true;
        code: 201;
        message: 'Stable promotion request submitted';
        data: {
            id: number;
        };
    };
};

export type PostAdminPackagesPackageNameStablePromotionRequestsResponse = PostAdminPackagesPackageNameStablePromotionRequestsResponses[keyof PostAdminPackagesPackageNameStablePromotionRequestsResponses];

export type GetAdminOsReleasesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
    };
    url: '/admin/os-releases';
};

export type GetAdminOsReleasesResponses = {
    /**
     * OS releases retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'OS releases retrieved';
        data: Array<{
            id: number;
            version: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        }>;
    };
};

export type GetAdminOsReleasesResponse = GetAdminOsReleasesResponses[keyof GetAdminOsReleasesResponses];

export type PostAdminOsReleasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/os-releases';
};

export type PostAdminOsReleasesResponses = {
    /**
     * OS release creation task enqueued
     */
    202: {
        success: true;
        code: 202;
        message: 'OS release creation task enqueued';
        data: {
            id: number;
            version: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        };
    };
};

export type PostAdminOsReleasesResponse = PostAdminOsReleasesResponses[keyof PostAdminOsReleasesResponses];

export type GetAdminOsReleasesVersionData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/admin/os-releases/{version}';
};

export type GetAdminOsReleasesVersionErrors = {
    /**
     * OS release not found
     */
    404: {
        success: false;
        code: 404;
        message: 'OS release not found';
    };
};

export type GetAdminOsReleasesVersionError = GetAdminOsReleasesVersionErrors[keyof GetAdminOsReleasesVersionErrors];

export type GetAdminOsReleasesVersionResponses = {
    /**
     * OS release retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'OS release retrieved';
        data: {
            id: number;
            version: string;
            created_at: number;
            published_at: number | null;
            publishing_status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
        };
    };
};

export type GetAdminOsReleasesVersionResponse = GetAdminOsReleasesVersionResponses[keyof GetAdminOsReleasesVersionResponses];

export type GetAdminStablePromotionRequestsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
    };
    url: '/admin/stable-promotion-requests';
};

export type GetAdminStablePromotionRequestsResponses = {
    /**
     * Stable promotion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion requests retrieved successfully';
        data: Array<{
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending' | 'approved' | 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        }>;
    };
};

export type GetAdminStablePromotionRequestsResponse = GetAdminStablePromotionRequestsResponses[keyof GetAdminStablePromotionRequestsResponses];

export type GetAdminStablePromotionRequestsRequestIdData = {
    body?: never;
    path: {
        requestID: number;
    };
    query?: never;
    url: '/admin/stable-promotion-requests/{requestID}';
};

export type GetAdminStablePromotionRequestsRequestIdErrors = {
    /**
     * Stable promotion request not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Stable promotion request not found';
    };
};

export type GetAdminStablePromotionRequestsRequestIdError = GetAdminStablePromotionRequestsRequestIdErrors[keyof GetAdminStablePromotionRequestsRequestIdErrors];

export type GetAdminStablePromotionRequestsRequestIdResponses = {
    /**
     * Stable promotion request retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable promotion request retrieved successfully';
        data: {
            id: number;
            package_id: number;
            package_release_id: number;
            status: 'pending' | 'approved' | 'denied';
            created_at: number;
            admin_note: string | null;
            package_name: string;
            package_release_version: string;
        };
    };
};

export type GetAdminStablePromotionRequestsRequestIdResponse = GetAdminStablePromotionRequestsRequestIdResponses[keyof GetAdminStablePromotionRequestsRequestIdResponses];

export type PostAdminStablePromotionRequestsRequestIdDecideData = {
    body?: {
        status: 'approved' | 'denied';
        admin_note: string;
    };
    path: {
        requestID: number;
    };
    query?: never;
    url: '/admin/stable-promotion-requests/{requestID}/decide';
};

export type PostAdminStablePromotionRequestsRequestIdDecideErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Stable promotion request not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Stable promotion request not found';
    };
};

export type PostAdminStablePromotionRequestsRequestIdDecideError = PostAdminStablePromotionRequestsRequestIdDecideErrors[keyof PostAdminStablePromotionRequestsRequestIdDecideErrors];

export type PostAdminStablePromotionRequestsRequestIdDecideResponses = {
    /**
     * Decided on stable promotion request successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Decided on stable promotion request successfully';
        data: null;
    };
};

export type PostAdminStablePromotionRequestsRequestIdDecideResponse = PostAdminStablePromotionRequestsRequestIdDecideResponses[keyof PostAdminStablePromotionRequestsRequestIdDecideResponses];

export type GetAdminTasksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/admin/tasks';
};

export type GetAdminTasksResponses = {
    /**
     * Scheduled tasks retrieved
     */
    200: {
        success: true;
        code: 200;
        message: 'Scheduled tasks retrieved';
        data: Array<{
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        }>;
    };
};

export type GetAdminTasksResponse = GetAdminTasksResponses[keyof GetAdminTasksResponses];

export type GetAdminTasksTaskIdData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/admin/tasks/{taskID}';
};

export type GetAdminTasksTaskIdErrors = {
    /**
     * Task with specified ID or Tag not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found';
    };
};

export type GetAdminTasksTaskIdError = GetAdminTasksTaskIdErrors[keyof GetAdminTasksTaskIdErrors];

export type GetAdminTasksTaskIdResponses = {
    /**
     * Task retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task retrieved successfully';
        data: {
            id: number;
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown> | null;
            message: string | null;
        };
    };
};

export type GetAdminTasksTaskIdResponse = GetAdminTasksTaskIdResponses[keyof GetAdminTasksTaskIdResponses];

export type GetAdminTasksTaskIdLogsData = {
    body?: never;
    path: {
        /**
         * Task ID
         */
        taskID: number;
    };
    query?: never;
    url: '/admin/tasks/{taskID}/logs';
};

export type GetAdminTasksTaskIdLogsErrors = {
    /**
     * Logs are not stored for this task
     */
    400: {
        success: false;
        code: 400;
        message: 'Logs are not stored for this task';
    };
    /**
     * Task with specified ID or Tag not found / Log file not found for this task
     */
    404: {
        success: false;
        code: 404;
        message: 'Task with specified ID or Tag not found / Log file not found for this task';
    };
};

export type GetAdminTasksTaskIdLogsError = GetAdminTasksTaskIdLogsErrors[keyof GetAdminTasksTaskIdLogsErrors];

export type GetAdminTasksTaskIdLogsResponses = {
    /**
     * Task logs retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task logs retrieved successfully';
        data: {
            logs: string;
        };
    };
};

export type GetAdminTasksTaskIdLogsResponse = GetAdminTasksTaskIdLogsResponses[keyof GetAdminTasksTaskIdLogsResponses];
