// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:4000' | 'https://api.repo.leios.dev' | (string & {});
};

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid username or password';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            token: string;
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            expires_at: number;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            token: string;
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'developer' | 'user';
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body?: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: unknown & unknown & unknown & unknown;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type PostAccountLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/logout';
};

export type PostAccountLogoutErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PostAccountLogoutError = PostAccountLogoutErrors[keyof PostAccountLogoutErrors];

export type PostAccountLogoutResponses = {
    /**
     * Logged out successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Logged out successfully';
        data: null;
    };
};

export type PostAccountLogoutResponse = PostAccountLogoutResponses[keyof PostAccountLogoutResponses];

export type GetDevPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dev/packages';
};

export type GetDevPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
        }>;
    };
};

export type GetDevPackagesResponse = GetDevPackagesResponses[keyof GetDevPackagesResponses];

export type PostDevPackagesData = {
    body?: {
        name: string;
        description: string;
        homepage_url: string;
    };
    path?: never;
    query?: never;
    url: '/dev/packages';
};

export type PostDevPackagesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Package with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Package with this name already exists';
    };
};

export type PostDevPackagesError = PostDevPackagesErrors[keyof PostDevPackagesErrors];

export type PostDevPackagesResponses = {
    /**
     * Package created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package created successfully';
        data: {
            name: string;
        };
    };
};

export type PostDevPackagesResponse = PostDevPackagesResponses[keyof PostDevPackagesResponses];

export type GetDevPackagesPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}';
};

export type GetDevPackagesPackageNameErrors = {
    /**
     * Package with specified name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified name not found';
    };
};

export type GetDevPackagesPackageNameError = GetDevPackagesPackageNameErrors[keyof GetDevPackagesPackageNameErrors];

export type GetDevPackagesPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
        };
    };
};

export type GetDevPackagesPackageNameResponse = GetDevPackagesPackageNameResponses[keyof GetDevPackagesPackageNameResponses];

export type PutDevPackagesPackageNameData = {
    body?: {
        description?: string;
        homepage_url?: string;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}';
};

export type PutDevPackagesPackageNameErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package with specified name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified name not found';
    };
};

export type PutDevPackagesPackageNameError = PutDevPackagesPackageNameErrors[keyof PutDevPackagesPackageNameErrors];

export type PutDevPackagesPackageNameResponses = {
    /**
     * Package updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package updated successfully';
        data: null;
    };
};

export type PutDevPackagesPackageNameResponse = PutDevPackagesPackageNameResponses[keyof PutDevPackagesPackageNameResponses];

export type GetDevPackagesPackageNameStableRequestsData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/dev/packages/{packageName}/stable-requests';
};

export type GetDevPackagesPackageNameStableRequestsErrors = {
    /**
     * Package with specified name not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package with specified name not found';
    };
};

export type GetDevPackagesPackageNameStableRequestsError = GetDevPackagesPackageNameStableRequestsErrors[keyof GetDevPackagesPackageNameStableRequestsErrors];

export type GetDevPackagesPackageNameStableRequestsResponses = {
    /**
     * Stable inclusion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable inclusion requests retrieved successfully';
        data: Array<{
            id: number;
            package_name: string;
            version: string;
            leios_patch: number | null;
            architecture: 'amd64' | 'arm64';
            requested_by: number;
            status: 'pending' | 'approved' | 'denied';
            reviewed_by: number | null;
            decision_reason: string | null;
        }>;
    };
};

export type GetDevPackagesPackageNameStableRequestsResponse = GetDevPackagesPackageNameStableRequestsResponses[keyof GetDevPackagesPackageNameStableRequestsResponses];

export type PostDevPackagesPackageNameStableRequestsData = {
    body?: {
        version: string;
        arch: 'amd64' | 'arm64';
        leios_patch?: number;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/stable-requests';
};

export type PostDevPackagesPackageNameStableRequestsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Release not found in archive repository
     */
    404: {
        success: false;
        code: 404;
        message: 'Release not found in archive repository';
    };
    /**
     * A pending request already exists or the release is already stable
     */
    409: {
        success: false;
        code: 409;
        message: 'A pending request already exists or the release is already stable';
    };
};

export type PostDevPackagesPackageNameStableRequestsError = PostDevPackagesPackageNameStableRequestsErrors[keyof PostDevPackagesPackageNameStableRequestsErrors];

export type PostDevPackagesPackageNameStableRequestsResponses = {
    /**
     * Stable inclusion request submitted
     */
    201: {
        success: true;
        code: 201;
        message: 'Stable inclusion request submitted';
        data: {
            id: number;
        };
    };
};

export type PostDevPackagesPackageNameStableRequestsResponse = PostDevPackagesPackageNameStableRequestsResponses[keyof PostDevPackagesPackageNameStableRequestsResponses];

export type GetDevPackagesPackageNameReleasesData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases';
};

export type GetDevPackagesPackageNameReleasesResponses = {
    /**
     * Package releases retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package releases retrieved successfully';
        data: {
            'leios-archive': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        version: string;
                        leios_patch?: number;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        version: string;
                        leios_patch?: number;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                };
            };
            'leios-testing': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        version: string;
                        leios_patch?: number;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        version: string;
                        leios_patch?: number;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                };
            };
            'leios-stable': {
                [key: string]: {
                    amd64?: {
                        name: string;
                        key: string;
                        version: string;
                        leios_patch?: number;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                    arm64?: {
                        name: string;
                        key: string;
                        version: string;
                        leios_patch?: number;
                        architecture: 'amd64' | 'arm64';
                        maintainer: string;
                        description: string;
                    };
                };
            };
        };
    };
};

export type GetDevPackagesPackageNameReleasesResponse = GetDevPackagesPackageNameReleasesResponses[keyof GetDevPackagesPackageNameReleasesResponses];

export type PostDevPackagesPackageNameReleasesVersionArchData = {
    body?: Blob | File;
    path: {
        packageName: string;
        version: string;
        arch: 'amd64' | 'arm64';
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{version}/{arch}';
};

export type PostDevPackagesPackageNameReleasesVersionArchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Package release with this version already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Package release with this version already exists';
    };
};

export type PostDevPackagesPackageNameReleasesVersionArchError = PostDevPackagesPackageNameReleasesVersionArchErrors[keyof PostDevPackagesPackageNameReleasesVersionArchErrors];

export type PostDevPackagesPackageNameReleasesVersionArchResponses = {
    /**
     * Package release created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Package release created successfully';
        data: {
            version: string;
            arch: 'amd64' | 'arm64';
        };
    };
};

export type PostDevPackagesPackageNameReleasesVersionArchResponse = PostDevPackagesPackageNameReleasesVersionArchResponses[keyof PostDevPackagesPackageNameReleasesVersionArchResponses];

export type GetDevPackagesPackageNameReleasesPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/dev/packages/{packageName}/releases/{packageName}';
};

export type GetDevPackagesPackageNameReleasesPackageNameErrors = {
    /**
     * Package release with specified version not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package release with specified version not found';
    };
};

export type GetDevPackagesPackageNameReleasesPackageNameError = GetDevPackagesPackageNameReleasesPackageNameErrors[keyof GetDevPackagesPackageNameReleasesPackageNameErrors];

export type GetDevPackagesPackageNameReleasesPackageNameResponses = {
    /**
     * Package release retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package release retrieved successfully';
        data: {
            amd64?: {
                name: string;
                key: string;
                version: string;
                leios_patch?: number;
                architecture: 'amd64' | 'arm64';
                maintainer: string;
                description: string;
            };
            arm64?: {
                name: string;
                key: string;
                version: string;
                leios_patch?: number;
                architecture: 'amd64' | 'arm64';
                maintainer: string;
                description: string;
            };
        };
    };
};

export type GetDevPackagesPackageNameReleasesPackageNameResponse = GetDevPackagesPackageNameReleasesPackageNameResponses[keyof GetDevPackagesPackageNameReleasesPackageNameResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'developer' | 'user';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body?: {
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'developer' | 'user';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersUserIdErrors = {
    /**
     * Cannot delete user while packages are assigned
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete user while packages are assigned';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersUserIdError = DeleteAdminUsersUserIdErrors[keyof DeleteAdminUsersUserIdErrors];

export type DeleteAdminUsersUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersUserIdResponse = DeleteAdminUsersUserIdResponses[keyof DeleteAdminUsersUserIdResponses];

export type GetAdminUsersUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersUserIdError = GetAdminUsersUserIdErrors[keyof GetAdminUsersUserIdErrors];

export type GetAdminUsersUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type GetAdminUsersUserIdResponse = GetAdminUsersUserIdResponses[keyof GetAdminUsersUserIdResponses];

export type PutAdminUsersUserIdData = {
    body?: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'developer' | 'user';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersUserIdError = PutAdminUsersUserIdErrors[keyof PutAdminUsersUserIdErrors];

export type PutAdminUsersUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
        };
    };
};

export type PutAdminUsersUserIdResponse = PutAdminUsersUserIdResponses[keyof PutAdminUsersUserIdResponses];

export type PutAdminUsersUserIdPasswordData = {
    body?: {
        password: string;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersUserIdPasswordError = PutAdminUsersUserIdPasswordErrors[keyof PutAdminUsersUserIdPasswordErrors];

export type PutAdminUsersUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersUserIdPasswordResponse = PutAdminUsersUserIdPasswordResponses[keyof PutAdminUsersUserIdPasswordResponses];

export type GetAdminPackagesStableRequestsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/admin/packages/stable-requests';
};

export type GetAdminPackagesStableRequestsResponses = {
    /**
     * Stable inclusion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable inclusion requests retrieved successfully';
        data: Array<{
            id: number;
            package_name: string;
            version: string;
            leios_patch: number | null;
            architecture: 'amd64' | 'arm64';
            requested_by: number;
            status: 'pending' | 'approved' | 'denied';
            reviewed_by: number | null;
            decision_reason: string | null;
        }>;
    };
};

export type GetAdminPackagesStableRequestsResponse = GetAdminPackagesStableRequestsResponses[keyof GetAdminPackagesStableRequestsResponses];

export type PostAdminPackagesStableRequestsRequestIdDecisionData = {
    body?: {
        decision: 'approve' | 'deny';
        reason?: string;
    };
    path: {
        requestId: number;
    };
    query?: never;
    url: '/admin/packages/stable-requests/{requestId}/decision';
};

export type PostAdminPackagesStableRequestsRequestIdDecisionErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Stable inclusion request not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Stable inclusion request not found';
    };
    /**
     * Stable inclusion request already resolved
     */
    409: {
        success: false;
        code: 409;
        message: 'Stable inclusion request already resolved';
    };
    /**
     * Failed to copy package into stable repository
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to copy package into stable repository';
    };
};

export type PostAdminPackagesStableRequestsRequestIdDecisionError = PostAdminPackagesStableRequestsRequestIdDecisionErrors[keyof PostAdminPackagesStableRequestsRequestIdDecisionErrors];

export type PostAdminPackagesStableRequestsRequestIdDecisionResponses = {
    /**
     * Stable inclusion request updated
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable inclusion request updated';
        data: {
            id: number;
            package_name: string;
            version: string;
            leios_patch: number | null;
            architecture: 'amd64' | 'arm64';
            requested_by: number;
            status: 'pending' | 'approved' | 'denied';
            reviewed_by: number | null;
            decision_reason: string | null;
        };
    };
};

export type PostAdminPackagesStableRequestsRequestIdDecisionResponse = PostAdminPackagesStableRequestsRequestIdDecisionResponses[keyof PostAdminPackagesStableRequestsRequestIdDecisionResponses];

export type GetAdminPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/packages';
};

export type GetAdminPackagesResponses = {
    /**
     * Packages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Packages retrieved successfully';
        data: Array<{
            name: string;
            owner_user_id: number;
            description: string;
            homepage_url: string;
        }>;
    };
};

export type GetAdminPackagesResponse = GetAdminPackagesResponses[keyof GetAdminPackagesResponses];

export type GetAdminPackagesPackageNameData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}';
};

export type GetAdminPackagesPackageNameErrors = {
    /**
     * Package not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package not found';
    };
};

export type GetAdminPackagesPackageNameError = GetAdminPackagesPackageNameErrors[keyof GetAdminPackagesPackageNameErrors];

export type GetAdminPackagesPackageNameResponses = {
    /**
     * Package retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Package retrieved successfully';
        data: {
            package: {
                name: string;
                owner_user_id: number;
                description: string;
                homepage_url: string;
            };
            releases: {
                'leios-archive': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            version: string;
                            leios_patch?: number;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            version: string;
                            leios_patch?: number;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
                'leios-testing': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            version: string;
                            leios_patch?: number;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            version: string;
                            leios_patch?: number;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
                'leios-stable': {
                    [key: string]: {
                        amd64?: {
                            name: string;
                            key: string;
                            version: string;
                            leios_patch?: number;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                        arm64?: {
                            name: string;
                            key: string;
                            version: string;
                            leios_patch?: number;
                            architecture: 'amd64' | 'arm64';
                            maintainer: string;
                            description: string;
                        };
                    };
                };
            };
            stableRequests: Array<{
                id: number;
                package_name: string;
                version: string;
                leios_patch: number | null;
                architecture: 'amd64' | 'arm64';
                requested_by: number;
                status: 'pending' | 'approved' | 'denied';
                reviewed_by: number | null;
                decision_reason: string | null;
            }>;
        };
    };
};

export type GetAdminPackagesPackageNameResponse = GetAdminPackagesPackageNameResponses[keyof GetAdminPackagesPackageNameResponses];

export type GetAdminPackagesPackageNameStableRequestsData = {
    body?: never;
    path: {
        packageName: string;
    };
    query?: {
        status?: 'pending' | 'approved' | 'denied';
    };
    url: '/admin/packages/{packageName}/stable-requests';
};

export type GetAdminPackagesPackageNameStableRequestsErrors = {
    /**
     * Package not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Package not found';
    };
};

export type GetAdminPackagesPackageNameStableRequestsError = GetAdminPackagesPackageNameStableRequestsErrors[keyof GetAdminPackagesPackageNameStableRequestsErrors];

export type GetAdminPackagesPackageNameStableRequestsResponses = {
    /**
     * Stable inclusion requests retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Stable inclusion requests retrieved successfully';
        data: Array<{
            id: number;
            package_name: string;
            version: string;
            leios_patch: number | null;
            architecture: 'amd64' | 'arm64';
            requested_by: number;
            status: 'pending' | 'approved' | 'denied';
            reviewed_by: number | null;
            decision_reason: string | null;
        }>;
    };
};

export type GetAdminPackagesPackageNameStableRequestsResponse = GetAdminPackagesPackageNameStableRequestsResponses[keyof GetAdminPackagesPackageNameStableRequestsResponses];

export type PostAdminPackagesPackageNameStableData = {
    body?: {
        version: string;
        arch: 'amd64' | 'arm64';
        leios_patch?: number;
    };
    path: {
        packageName: string;
    };
    query?: never;
    url: '/admin/packages/{packageName}/stable';
};

export type PostAdminPackagesPackageNameStableErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Package version not found in archive
     */
    404: {
        success: false;
        code: 404;
        message: 'Package version not found in archive';
    };
    /**
     * Package version already exists in stable
     */
    409: {
        success: false;
        code: 409;
        message: 'Package version already exists in stable';
    };
    /**
     * Failed to copy package into stable repository
     */
    500: {
        success: false;
        code: 500;
        message: 'Failed to copy package into stable repository';
    };
};

export type PostAdminPackagesPackageNameStableError = PostAdminPackagesPackageNameStableErrors[keyof PostAdminPackagesPackageNameStableErrors];

export type PostAdminPackagesPackageNameStableResponses = {
    /**
     * Package copied into stable repository
     */
    200: {
        success: true;
        code: 200;
        message: 'Package copied into stable repository';
        data: {
            version: string;
            arch: 'amd64' | 'arm64';
            leios_patch?: number;
            copied: true;
        };
    };
};

export type PostAdminPackagesPackageNameStableResponse = PostAdminPackagesPackageNameStableResponses[keyof PostAdminPackagesPackageNameStableResponses];
