// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zGetPublicPackagesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Packages retrieved successfully
 */
export const zGetPublicPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Packages retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        latest_stable_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_stable_release_arm64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_arm64: z.union([
            z.string(),
            z.null()
        ])
    }))
});

export const zGetPublicPackagesPackageNameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string().min(1)
    }),
    query: z.optional(z.object({
        repo: z.optional(z.enum([
            'leios-archive',
            'leios-testing',
            'leios-stable'
        ]))
    }))
});

/**
 * Package retrieved successfully
 */
export const zGetPublicPackagesPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package retrieved successfully'),
    data: z.object({
        package: z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            name: z.string(),
            owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            description: z.string(),
            homepage_url: z.string(),
            requires_patching: z.boolean(),
            latest_stable_release_amd64: z.union([
                z.string(),
                z.null()
            ]),
            latest_stable_release_arm64: z.union([
                z.string(),
                z.null()
            ]),
            latest_testing_release_amd64: z.union([
                z.string(),
                z.null()
            ]),
            latest_testing_release_arm64: z.union([
                z.string(),
                z.null()
            ])
        }),
        releases: z.object({
            'leios-archive': z.record(z.string(), z.object({
                amd64: z.optional(z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum(['amd64', 'arm64']),
                    maintainer: z.string(),
                    description: z.string()
                })),
                arm64: z.optional(z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum(['amd64', 'arm64']),
                    maintainer: z.string(),
                    description: z.string()
                }))
            })),
            'leios-testing': z.record(z.string(), z.object({
                amd64: z.optional(z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum(['amd64', 'arm64']),
                    maintainer: z.string(),
                    description: z.string()
                })),
                arm64: z.optional(z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum(['amd64', 'arm64']),
                    maintainer: z.string(),
                    description: z.string()
                }))
            })),
            'leios-stable': z.record(z.string(), z.object({
                amd64: z.optional(z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum(['amd64', 'arm64']),
                    maintainer: z.string(),
                    description: z.string()
                })),
                arm64: z.optional(z.object({
                    name: z.string(),
                    key: z.string(),
                    versionWithLeiosPatch: z.string(),
                    architecture: z.enum(['amd64', 'arm64']),
                    maintainer: z.string(),
                    description: z.string()
                }))
            }))
        })
    })
});

export const zGetPublicPackagesPackageNameReleasesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string().min(1)
    }),
    query: z.optional(z.object({
        repo: z.optional(z.enum([
            'leios-archive',
            'leios-testing',
            'leios-stable'
        ]))
    }))
});

/**
 * Package releases retrieved successfully
 */
export const zGetPublicPackagesPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package releases retrieved successfully'),
    data: z.object({
        'leios-archive': z.record(z.string(), z.object({
            amd64: z.optional(z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum(['amd64', 'arm64']),
                maintainer: z.string(),
                description: z.string()
            })),
            arm64: z.optional(z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum(['amd64', 'arm64']),
                maintainer: z.string(),
                description: z.string()
            }))
        })),
        'leios-testing': z.record(z.string(), z.object({
            amd64: z.optional(z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum(['amd64', 'arm64']),
                maintainer: z.string(),
                description: z.string()
            })),
            arm64: z.optional(z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum(['amd64', 'arm64']),
                maintainer: z.string(),
                description: z.string()
            }))
        })),
        'leios-stable': z.record(z.string(), z.object({
            amd64: z.optional(z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum(['amd64', 'arm64']),
                maintainer: z.string(),
                description: z.string()
            })),
            arm64: z.optional(z.object({
                name: z.string(),
                key: z.string(),
                versionWithLeiosPatch: z.string(),
                architecture: z.enum(['amd64', 'arm64']),
                maintainer: z.string(),
                description: z.string()
            }))
        }))
    })
});

export const zPostAuthLoginData = z.object({
    body: z.optional(z.object({
        username: z.string(),
        password: z.string()
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        token: z.string()
    })
});

export const zGetAuthSessionData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Session info retrieved successfully
 */
export const zGetAuthSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session info retrieved successfully'),
    data: z.object({
        user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        user_role: z.enum([
            'admin',
            'developer',
            'user'
        ]),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zPostAuthLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

export const zPostAuthResetPasswordData = z.object({
    body: z.optional(z.object({
        reset_token: z.string().min(1),
        new_password: z.intersection(z.unknown(), z.unknown(), z.unknown(), z.unknown())
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Password has been reset successfully
 */
export const zPostAuthResetPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password has been reset successfully'),
    data: z.null()
});

export const zPostAuthResetPasswordRequestData = z.object({
    body: z.optional(z.object({
        email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * If the username exists, a password reset has been requested
 */
export const zPostAuthResetPasswordRequestResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('If the username exists, a password reset has been requested'),
    data: z.null()
});

export const zDeleteAccountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Account deleted successfully
 */
export const zDeleteAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account deleted successfully'),
    data: z.null()
});

export const zGetAccountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Account information retrieved successfully
 */
export const zGetAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zPutAccountData = z.object({
    body: z.optional(z.object({
        username: z.optional(z.string().min(5).max(30).regex(/^[a-zA-Z0-9_]+$/)),
        display_name: z.optional(z.string()),
        email: z.optional(z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Account information updated successfully
 */
export const zPutAccountResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Account information updated successfully'),
    data: z.null()
});

export const zPutAccountPasswordData = z.object({
    body: z.optional(z.object({
        current_password: z.string(),
        new_password: z.intersection(z.unknown(), z.unknown(), z.unknown(), z.unknown())
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Password changed successfully
 */
export const zPutAccountPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password changed successfully'),
    data: z.null()
});

export const zGetAccountApikeysData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * API keys retrieved successfully
 */
export const zGetAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API keys retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        description: z.string(),
        expires_at: z.union([
            z.int().gte(-9007199254740991).lte(9007199254740991),
            z.null()
        ])
    }))
});

export const zPostAccountApikeysData = z.object({
    body: z.optional(z.object({
        description: z.string(),
        expires_at: z.union([
            z.literal('7d'),
            z.literal('30d'),
            z.literal('90d'),
            z.literal('180d'),
            z.literal('365d'),
            z.null()
        ])
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * API key created successfully
 */
export const zPostAccountApikeysResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key created successfully'),
    data: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zDeleteAccountApikeysApiKeyIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        apiKeyID: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * API key deleted successfully
 */
export const zDeleteAccountApikeysApiKeyIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('API key deleted successfully'),
    data: z.null()
});

export const zGetDevPackagesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Packages retrieved successfully
 */
export const zGetDevPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Packages retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        latest_stable_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_stable_release_arm64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_arm64: z.union([
            z.string(),
            z.null()
        ])
    }))
});

export const zPostDevPackagesData = z.object({
    body: z.optional(z.object({
        id: z.optional(z.int().gte(-9007199254740991).lte(9007199254740991)),
        name: z.string().regex(/^[a-z0-9][a-z0-9+.-]{1,62}$/),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.optional(z.boolean()),
        latest_stable_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_stable_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Package created successfully
 */
export const zPostDevPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package created successfully'),
    data: z.null()
});

export const zGetDevPackagesPackageNameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Package retrieved successfully
 */
export const zGetDevPackagesPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        latest_stable_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_stable_release_arm64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_arm64: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPutDevPackagesPackageNameData = z.object({
    body: z.optional(z.object({
        id: z.optional(z.int().gte(-9007199254740991).lte(9007199254740991)),
        description: z.optional(z.string()),
        homepage_url: z.optional(z.string()),
        requires_patching: z.optional(z.boolean()),
        latest_stable_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_stable_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Package updated successfully
 */
export const zPutDevPackagesPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package updated successfully'),
    data: z.null()
});

export const zGetDevPackagesPackageNameReleasesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Package releases retrieved successfully
 */
export const zGetDevPackagesPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package releases retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architecture: z.array(z.enum(['amd64', 'arm64']))
    }))
});

export const zGetDevPackagesPackageNameReleasesVersionWithLeiosPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Package release retrieved successfully
 */
export const zGetDevPackagesPackageNameReleasesVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architecture: z.array(z.enum(['amd64', 'arm64']))
    })
});

export const zPostDevPackagesPackageNameReleasesVersionWithLeiosPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Package release created successfully
 */
export const zPostDevPackagesPackageNameReleasesVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release created successfully'),
    data: z.null()
});

export const zPostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchData = z.object({
    body: z.optional(z.object({
        file: z.string().min(1).max(1073741824)
    })),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
        arch: z.enum(['amd64', 'arm64'])
    }),
    query: z.optional(z.never())
});

/**
 * Package release file uploaded successfully
 */
export const zPostDevPackagesPackageNameReleasesVersionWithLeiosPatchArchResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release file uploaded successfully'),
    data: z.null()
});

export const zGetDevPackagesPackageNameStablePromotionRequestsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.object({
        status: z.optional(z.enum([
            'pending',
            'approved',
            'denied'
        ]))
    }))
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetDevPackagesPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            admin_note: z.null()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            admin_note: z.union([
                z.string(),
                z.null()
            ])
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            admin_note: z.string()
        })
    ]))
});

export const zPostDevPackagesPackageNameStablePromotionRequestsData = z.object({
    body: z.optional(z.object({
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991)
    })),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Stable promotion request submitted
 */
export const zPostDevPackagesPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Stable promotion request submitted'),
    data: z.object({
        id: z.number()
    })
});

export const zGetDevTasksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Scheduled tasks retrieved
 */
export const zGetDevTasksResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Scheduled tasks retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        tag: z.string(),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.union([
            z.int().gte(-9007199254740991).lte(9007199254740991),
            z.null()
        ]),
        result: z.union([
            z.union([
                z.union([
                    z.string(),
                    z.number(),
                    z.boolean(),
                    z.null()
                ]),
                z.record(z.string(), z.unknown()),
                z.array(z.unknown())
            ]),
            z.null()
        ]),
        message: z.union([
            z.string(),
            z.null()
        ])
    }))
});

export const zGetDevTasksTaskIDorTagData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        taskIDorTag: z.union([
            z.int().gt(0).lte(9007199254740991),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Task retrieved successfully
 */
export const zGetDevTasksTaskIDorTagResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        tag: z.string(),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.union([
            z.int().gte(-9007199254740991).lte(9007199254740991),
            z.null()
        ]),
        result: z.union([
            z.union([
                z.union([
                    z.string(),
                    z.number(),
                    z.boolean(),
                    z.null()
                ]),
                z.record(z.string(), z.unknown()),
                z.array(z.unknown())
            ]),
            z.null()
        ]),
        message: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zGetDevTasksTaskIDorTagLogsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        taskIDorTag: z.union([
            z.int().gt(0).lte(9007199254740991),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Task logs retrieved successfully
 */
export const zGetDevTasksTaskIDorTagLogsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task logs retrieved successfully'),
    data: z.object({
        logs: z.string()
    })
});

export const zGetAdminUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        role: z.optional(z.enum([
            'admin',
            'developer',
            'user'
        ])),
        search: z.optional(z.string().min(1).max(64)),
        limit: z.optional(z.int().gte(1).lte(100)),
        offset: z.optional(z.int().gte(0).lte(9007199254740991))
    }))
});

/**
 * Users retrieved successfully
 */
export const zGetAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Users retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    }))
});

export const zPostAdminUsersData = z.object({
    body: z.optional(z.object({
        username: z.string().min(5).max(30).regex(/^[a-zA-Z0-9_]+$/),
        display_name: z.string().min(1).max(64),
        email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        role: z.optional(z.enum([
            'admin',
            'developer',
            'user'
        ])),
        password: z.string().min(8).max(128)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * User created successfully
 */
export const zPostAdminUsersResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('User created successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zDeleteAdminUsersUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.optional(z.never())
});

/**
 * User deleted successfully
 */
export const zDeleteAdminUsersUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User deleted successfully'),
    data: z.null()
});

export const zGetAdminUsersUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.optional(z.never())
});

/**
 * User retrieved successfully
 */
export const zGetAdminUsersUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zPutAdminUsersUserIdData = z.object({
    body: z.optional(z.object({
        username: z.optional(z.string()),
        display_name: z.optional(z.string()),
        email: z.optional(z.string()),
        role: z.optional(z.enum([
            'admin',
            'developer',
            'user'
        ]))
    })),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.optional(z.never())
});

/**
 * User updated successfully
 */
export const zPutAdminUsersUserIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User updated successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        username: z.string(),
        display_name: z.string(),
        email: z.string(),
        role: z.enum([
            'admin',
            'developer',
            'user'
        ])
    })
});

export const zPutAdminUsersUserIdPasswordData = z.object({
    body: z.optional(z.object({
        password: z.intersection(z.unknown(), z.unknown(), z.unknown(), z.unknown())
    })),
    path: z.object({
        userId: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.optional(z.never())
});

/**
 * Password reset successfully
 */
export const zPutAdminUsersUserIdPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password reset successfully'),
    data: z.null()
});

export const zGetAdminPackagesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Packages retrieved successfully
 */
export const zGetAdminPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Packages retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        latest_stable_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_stable_release_arm64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_arm64: z.union([
            z.string(),
            z.null()
        ])
    }))
});

export const zPostAdminPackagesData = z.object({
    body: z.optional(z.object({
        id: z.optional(z.int().gte(-9007199254740991).lte(9007199254740991)),
        name: z.string().regex(/^[a-z0-9][a-z0-9+.-]{1,62}$/),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.optional(z.boolean()),
        latest_stable_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_stable_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Package created successfully
 */
export const zPostAdminPackagesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package created successfully'),
    data: z.null()
});

export const zDeleteAdminPackagesPackageNameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Package deleted successfully
 */
export const zDeleteAdminPackagesPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package deleted successfully'),
    data: z.null()
});

export const zGetAdminPackagesPackageNameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Package retrieved successfully
 */
export const zGetAdminPackagesPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        name: z.string(),
        owner_user_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        description: z.string(),
        homepage_url: z.string(),
        requires_patching: z.boolean(),
        latest_stable_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_stable_release_arm64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_amd64: z.union([
            z.string(),
            z.null()
        ]),
        latest_testing_release_arm64: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPutAdminPackagesPackageNameData = z.object({
    body: z.optional(z.object({
        id: z.optional(z.int().gte(-9007199254740991).lte(9007199254740991)),
        description: z.optional(z.string()),
        homepage_url: z.optional(z.string()),
        requires_patching: z.optional(z.boolean()),
        latest_stable_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_stable_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_amd64: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        latest_testing_release_arm64: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Package updated successfully
 */
export const zPutAdminPackagesPackageNameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package updated successfully'),
    data: z.null()
});

export const zGetAdminPackagesPackageNameReleasesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Package releases retrieved successfully
 */
export const zGetAdminPackagesPackageNameReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package releases retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architecture: z.array(z.enum(['amd64', 'arm64']))
    }))
});

export const zDeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Package release deleted successfully
 */
export const zDeleteAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release deleted successfully'),
    data: z.null()
});

export const zGetAdminPackagesPackageNameReleasesVersionWithLeiosPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Package release retrieved successfully
 */
export const zGetAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Package release retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        versionWithLeiosPatch: z.string(),
        architecture: z.array(z.enum(['amd64', 'arm64']))
    })
});

export const zPostAdminPackagesPackageNameReleasesVersionWithLeiosPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Package release created successfully
 */
export const zPostAdminPackagesPackageNameReleasesVersionWithLeiosPatchResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release created successfully'),
    data: z.null()
});

export const zPostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchData = z.object({
    body: z.optional(z.object({
        file: z.string().min(1).max(1073741824)
    })),
    path: z.object({
        packageName: z.string(),
        versionWithLeiosPatch: z.string().regex(/^(?:[0-9][0-9A-Za-z.+~\-]*leios\d+(?:\.\d+){0,2}|(?!.*leios)[0-9][0-9A-Za-z.+~\-]*)$/),
        arch: z.enum(['amd64', 'arm64'])
    }),
    query: z.optional(z.never())
});

/**
 * Package release file uploaded successfully
 */
export const zPostAdminPackagesPackageNameReleasesVersionWithLeiosPatchArchResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Package release file uploaded successfully'),
    data: z.null()
});

export const zGetAdminPackagesPackageNameStablePromotionRequestsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.object({
        status: z.optional(z.enum([
            'pending',
            'approved',
            'denied'
        ]))
    }))
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetAdminPackagesPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.union([
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('pending'),
            admin_note: z.null()
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('approved'),
            admin_note: z.union([
                z.string(),
                z.null()
            ])
        }),
        z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
            status: z.literal('denied'),
            admin_note: z.string()
        })
    ]))
});

export const zPostAdminPackagesPackageNameStablePromotionRequestsData = z.object({
    body: z.optional(z.object({
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991)
    })),
    path: z.object({
        packageName: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Stable promotion request submitted
 */
export const zPostAdminPackagesPackageNameStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Stable promotion request submitted'),
    data: z.object({
        id: z.number()
    })
});

export const zGetAdminOsReleasesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OS releases retrieved
 */
export const zGetAdminOsReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS releases retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        published_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    }))
});

export const zPostAdminOsReleasesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OS release creation task enqueued
 */
export const zPostAdminOsReleasesResponse = z.object({
    success: z.literal(true),
    code: z.literal(202),
    message: z.literal('OS release creation task enqueued'),
    data: z.object({
        version: z.string(),
        taskID: z.number(),
        taskTag: z.string()
    })
});

export const zGetAdminOsReleasesVersionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        version: z.string().regex(/^\d{4}\.\d{2}\.\d{2}$/)
    }),
    query: z.optional(z.never())
});

/**
 * OS release retrieved
 */
export const zGetAdminOsReleasesVersionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OS release retrieved'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        version: z.string(),
        published_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

export const zGetAdminStablePromotionRequestsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Stable promotion requests retrieved successfully
 */
export const zGetAdminStablePromotionRequestsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion requests retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]),
        admin_note: z.union([
            z.string(),
            z.null()
        ]),
        package_name: z.string(),
        package_release_version: z.string()
    }))
});

export const zGetAdminStablePromotionRequestsRequestIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        requestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.optional(z.never())
});

/**
 * Stable promotion request retrieved successfully
 */
export const zGetAdminStablePromotionRequestsRequestIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Stable promotion request retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        package_release_id: z.int().gte(-9007199254740991).lte(9007199254740991),
        status: z.enum([
            'pending',
            'approved',
            'denied'
        ]),
        admin_note: z.union([
            z.string(),
            z.null()
        ]),
        package_name: z.string(),
        package_release_version: z.string()
    })
});

export const zPostAdminStablePromotionRequestsRequestIdDecideData = z.object({
    body: z.optional(z.object({
        status: z.enum(['approved', 'denied']),
        admin_note: z.string()
    })),
    path: z.object({
        requestID: z.int().gt(0).lte(9007199254740991)
    }),
    query: z.optional(z.never())
});

/**
 * Decided on stable promotion request successfully
 */
export const zPostAdminStablePromotionRequestsRequestIdDecideResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Decided on stable promotion request successfully'),
    data: z.null()
});

export const zGetAdminTasksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Scheduled tasks retrieved
 */
export const zGetAdminTasksResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Scheduled tasks retrieved'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        tag: z.string(),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.union([
            z.int().gte(-9007199254740991).lte(9007199254740991),
            z.null()
        ]),
        result: z.union([
            z.union([
                z.union([
                    z.string(),
                    z.number(),
                    z.boolean(),
                    z.null()
                ]),
                z.record(z.string(), z.unknown()),
                z.array(z.unknown())
            ]),
            z.null()
        ]),
        message: z.union([
            z.string(),
            z.null()
        ])
    }))
});

export const zGetAdminTasksTaskIDorTagData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        taskIDorTag: z.union([
            z.int().gt(0).lte(9007199254740991),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Task retrieved successfully
 */
export const zGetAdminTasksTaskIDorTagResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        tag: z.string(),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.union([
            z.int().gte(-9007199254740991).lte(9007199254740991),
            z.null()
        ]),
        result: z.union([
            z.union([
                z.union([
                    z.string(),
                    z.number(),
                    z.boolean(),
                    z.null()
                ]),
                z.record(z.string(), z.unknown()),
                z.array(z.unknown())
            ]),
            z.null()
        ]),
        message: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zGetAdminTasksTaskIDorTagLogsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        taskIDorTag: z.union([
            z.int().gt(0).lte(9007199254740991),
            z.string()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Task logs retrieved successfully
 */
export const zGetAdminTasksTaskIDorTagLogsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task logs retrieved successfully'),
    data: z.object({
        logs: z.string()
    })
});
